namespace FSharp.Discord.Types

// https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes
[<RequireQualifiedAccess>]
type GatewayCloseEventCode =
    | UNKNOWN_ERROR         = 4000
    | UNKNOWN_OPCODE        = 4001
    | DECODE_ERROR          = 4002
    | NOT_AUTHENTICATED     = 4003
    | AUTHENTICATION_FAILED = 4004
    | ALREADY_AUTHENTICATED = 4005
    | INVALID_SEQ           = 4007
    | RATE_LIMITED          = 4008
    | SESSION_TIMED_OUT     = 4009
    | INVALID_SHARD         = 4010
    | SHARDING_REQUIRED     = 4011
    | INVALID_API_VERSION   = 4012
    | INVALID_INTENTS       = 4013
    | DISALLOWED_INTENTS    = 4014

module GatewayCloseEventCode =
    let shouldReconnect (code: GatewayCloseEventCode) =
        match code with
        | GatewayCloseEventCode.UNKNOWN_ERROR -> true
        | GatewayCloseEventCode.UNKNOWN_OPCODE -> true
        | GatewayCloseEventCode.DECODE_ERROR -> true
        | GatewayCloseEventCode.NOT_AUTHENTICATED -> true
        | GatewayCloseEventCode.AUTHENTICATION_FAILED -> false
        | GatewayCloseEventCode.ALREADY_AUTHENTICATED -> true
        | GatewayCloseEventCode.INVALID_SEQ -> true
        | GatewayCloseEventCode.RATE_LIMITED -> true
        | GatewayCloseEventCode.SESSION_TIMED_OUT -> true
        | GatewayCloseEventCode.INVALID_SHARD -> false
        | GatewayCloseEventCode.SHARDING_REQUIRED -> false
        | GatewayCloseEventCode.INVALID_API_VERSION -> false
        | GatewayCloseEventCode.INVALID_INTENTS -> false
        | GatewayCloseEventCode.DISALLOWED_INTENTS -> false
        | v when int v = 1000 || int v = 1001 -> false
        | _ -> true

// https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-opcodes
[<RequireQualifiedAccess>]
type GatewayOpcode =
    | DISPATCH                  = 0
    | HEARTBEAT                 = 1
    | IDENTIFY                  = 2
    | PRESENCE_UPDATE           = 3
    | VOICE_STATE_UPDATE        = 4
    | RESUME                    = 6
    | RECONNECT                 = 7
    | REQUEST_GUILD_MEMBERS     = 8
    | INVALID_SESSION           = 9
    | HELLO                     = 10
    | HEARTBEAT_ACK             = 11
    | REQUEST_SOUNDBOARD_SOUNDS = 31
    
// https://discord.com/developers/docs/topics/opcodes-and-status-codes#json-json-error-codes
[<RequireQualifiedAccess>]
type JsonErrorCode =
    | UNKNOWN_ERROR                                                = 0
    | UNKNOWN_ACCOUNT                                              = 10001
    | UNKNOWN_APPLICATION                                          = 10002
    | UNKNOWN_CHANNEL                                              = 10003
    | UNKNOWN_GUILD                                                = 10004
    | UNKNOWN_INTEGRATION                                          = 10005
    | UNKNOWN_INVITE                                               = 10006
    | UNKNOWN_MEMBER                                               = 10007
    | UNKNOWN_MESSAGE                                              = 10008
    | UNKNOWN_PERMISSION_OVERWRITE                                 = 10009
    | UNKNOWN_PROVIDER                                             = 10010
    | UNKNOWN_ROLE                                                 = 10011
    | UNKNOWN_TOKEN                                                = 10012
    | UNKNOWN_USER                                                 = 10013
    | UNKNOWN_EMOJI                                                = 10014
    | UNKNOWN_WEBHOOK                                              = 10015
    | UNKNOWN_BAN                                                  = 10026
    | UNKNOWN_SKU                                                  = 10027
    | UNKNOWN_STORE_LISTING                                        = 10028
    | UNKNOWN_ENTITLEMENT                                          = 10029
    | UNKNOWN_BUILD                                                = 10030
    | UNKNOWN_LOBBY                                                = 10031
    | UNKNOWN_BRANCH                                               = 10032
    | UNKNOWN_STORE_DIRECTORY_LAYOUT                               = 10033
    | UNKNOWN_REDISTRIBUTABLE                                      = 10036
    | UNKNOWN_GIFT_CODE                                            = 10038
    | UNKNOWN_STREAM                                               = 10049
    | UNKNOWN_PREMIUM_SERVER_SUBSCRIBE_COOLDOWN                    = 10050
    | UNKNOWN_GUILD_TEMPLATE                                       = 10057
    | UNKNOWN_DISCOVERABLE_SERVER_CATEGORY                         = 10059
    | UNKNOWN_STICKER                                              = 10060
    | UNKNOWN_STICKER_PACK                                         = 10061
    | UNKNOWN_INTERACTION                                          = 10062
    | UNKNOWN_APPLICATION_COMMAND                                  = 10063
    | UNKNOWN_VOICE_STATE                                          = 10065
    | UNKNOWN_APPLICATION_COMMAND_PERMISSIONS                      = 10066
    | UNKNOWN_STAGE_INSTANCE                                       = 10067
    | UNKNOWN_GUILD_MEMBER_VERIFICATION_FORM                       = 10068
    | UNKNOWN_GUILD_WELCOME_SCREEN                                 = 10069
    | UNKNOWN_GUILD_SCHEDULED_EVENT                                = 10070
    | UNKNOWN_GUILD_SCHEDULED_EVENT_USER                           = 10071
    | UNKNOWN_TAG                                                  = 10087
    | UNKNOWN_SOUND                                                = 10097
    | BOT_CANNOT_USE_ENDPOINT                                      = 20001
    | BOT_ONLY_ENDPOINT                                            = 20002
    | RECIPIENT_NOT_ACCEPTING_EXPLICIT_CONTENT                     = 20009
    | NOT_AUTHORIZED                                               = 20012
    | SLOWMODE_RATE_LIMIT                                          = 20016
    | OWNER_ACTION_ONLY                                            = 20018
    | ANNOUNCEMENT_EDIT_RATE_LIMITED                               = 20022
    | UNDER_MINIMUM_AGE                                            = 20024
    | CHANNEL_WRITE_RATE_LIMIT                                     = 20028
    | SERVER_WRITE_RATE_LIMIT                                      = 20029
    | DISALLOWED_WORDS_IN_SERVER_INFO                              = 20031
    | GUILD_PREMIUM_LEVEL_TOO_LOW                                  = 20035
    | MAX_GUILDS_REACHED                                           = 30001
    | MAX_FRIENDS_REACHED                                          = 30002
    | MAX_CHANNEL_PINS_REACHED                                     = 30003
    | MAX_RECIPIENTS_REACHED                                       = 30004
    | MAX_GUILD_ROLES_REACHED                                      = 30005
    | MAX_WEBHOOKS_REACHED                                         = 30007
    | MAX_EMOJIS_REACHED                                           = 30008
    | MAX_REACTIONS_REACHED                                        = 30010
    | MAX_GROUP_DMS_REACHED                                        = 30011
    | MAX_GUILD_CHANNELS_REACHED                                   = 30013
    | MAX_ATTACHMENTS_REACHED                                      = 30015
    | MAX_INVITES_REACHED                                          = 30016
    | MAX_ANIMATED_EMOJIS_REACHED                                  = 30018
    | MAX_SERVER_MEMBERS_REACHED                                   = 30019
    | MAX_SERVER_CATEGORIES_REACHED                                = 30030
    | GUILD_TEMPLATE_ALREADY_EXISTS                                = 30031
    | MAX_APPLICATION_COMMANDS_REACHED                             = 30032
    | MAX_THREAD_PARTICIPANTS_REACHED                              = 30033
    | MAX_DAILY_APPLICATION_COMMAND_CREATES_REACHED                = 30034
    | MAX_NON_GUILD_MEMBER_BANS_REACHED                            = 30035
    | MAX_BAN_FETCHES_REACHED                                      = 30037
    | MAX_UNCOMPLETED_GUILD_SCHEDULED_EVENTS_REACHED               = 30038
    | MAX_STICKERS_REACHED                                         = 30039
    | MAX_PRUNE_REQUESTS_REACHED                                   = 30040
    | MAX_GUILD_WIDGET_SETTINGS_UPDATES_REACHED                    = 30042
    | MAX_SOUNDBOARD_SOUNDS_REACHED                                = 30045
    | MAX_MESSAGE_EDITS_OVER_ONE_HOUR_REACHED                      = 30046
    | MAX_FORUM_PINNED_THREADS_REACHED                             = 30047
    | MAX_FORUM_CHANNEL_TAGS_REACHED                               = 30048
    | BITRATE_TOO_HIGH_FOR_CHANNEL_TYPE                            = 30052
    | MAX_PREMIUM_EMOJIS_REACHED                                   = 30056
    | MAX_WEBHOOKS_PER_GUILD_REACHED                               = 30058
    | MAX_CHANNEL_PERMISSION_OVERWRITES_REACHED                    = 30060
    | GUILD_CHANNELS_TOO_LARGE                                     = 30061
    | UNAUTHORIZED                                                 = 40001
    | ACCOUNT_VERIFICATION_REQUIRED                                = 40002
    | OPENING_DIRECT_MESSAGES_TOO_FAST                             = 40003
    | SEND_MESSAGES_TEMPORARILY_DISABLED                           = 40004
    | REQUEST_ENTITY_TOO_LARGE                                     = 40005
    | FEATURE_TEMPORARILY_DISABLED_SERVER_SIDE                     = 40006
    | USER_BANNED                                                  = 40007
    | CONNECTION_REVOKED                                           = 40012
    | ONLY_CONSUMABLE_SKUS_CAN_BE_CONSUMED                         = 40018
    | CAN_ONLY_DELETE_SANDBOX_ENTITLEMENTS                         = 40019
    | TARGET_USER_NOT_CONNECTED_TO_VOICE                           = 40032
    | MESSAGE_ALREADY_CROSSPOSTED                                  = 40033
    | APPLICATION_COMMAND_NAME_ALREADY_EXISTS                      = 40041
    | APPLICATION_INTERACTION_FAILED_TO_SEND                       = 40043
    | CANNOT_SEND_MESSAGE_IN_FORUM_CHANNEL                         = 40058
    | INTERACTION_ALREADY_ACKNOWLEDGED                             = 40060
    | TAG_NAMES_MUST_BE_UNIQUE                                     = 40061
    | SERVICE_RESOURCE_BEING_RATE_LIMITED                          = 40062
    | NO_AVAILABLE_TAGS_FOR_NON_MODERATORS                         = 40066
    | TAG_REQUIRED_TO_CREATE_FORUM_POST                            = 40067
    | ENTITLEMENT_ALREADY_GRANTED                                  = 40074
    | INTERACTION_MAX_FOLLOW_UP_MESSAGES                           = 40094
    | CLOUDFLARE_USER_AGENT_BLOCKED                                = 40333
    | MISSING_ACCESS                                               = 50001
    | CANNOT_EXECUTE_ACTION_IN_DM_CHANNEL                          = 50003
    | GUILD_WIDGET_DISABLED                                        = 50004
    | CANNOT_EDIT_OTHER_USERS_MESSAGE                              = 50006
    | CANNOT_SEND_MESSAGE_TO_THIS_USER                             = 50007
    | CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL                     = 50008
    | CHANNEL_VERIFICATION_LEVEL_TOO_HIGH_TO_ACCESS                = 50009
    | OAUTH2_APPLICATION_DOES_NOT_HAVE_BOT                         = 50010
    | OAUTH2_APPLICATION_LIMIT_REACHED                             = 50011
    | INVALID_OAUTH2_STATE                                         = 50012
    | LACK_PERMISSIONS                                             = 50013
    | INVALID_AUTHENTICATION_TOKEN                                 = 50014
    | NOTE_TOO_LONG                                                = 50015
    | TOO_FEW_MESSAGES_TO_DELETE                                   = 50016
    | INVALID_MFA_LEVEL                                            = 50017
    | CANNOT_PIN_MESSAGES_FROM_OTHER_CHANNELS                      = 50019
    | INVALID_OR_TAKEN_INVITE_CODE                                 = 50020
    | CANNOT_EXECUTE_ACTION_ON_SYSTEM_MESSAGE                      = 50021
    | CANNOT_EXECUTE_ACTION_ON_THIS_CHANNEL_TYPE                   = 50024
    | INVALID_OAUTH2_ACCESS_TOKEN_PROVIDED                         = 50025
    | MISSING_REQUIRED_OAUTH2_SCOPE                                = 50026
    | INVALID_WEBHOOK_TOKEN_PROVIDED                               = 50027
    | INVALID_ROLE                                                 = 50028
    | INVALID_RECIPIENT                                            = 50033
    | MESSAGE_TOO_OLD_TO_BULK_DELETE                               = 50034
    | INVALID_FORM_BODY_OR_CONTENT_TYPE                            = 50035
    | INVITE_ACCEPTED_TO_GUILD_APPLICATION_BOT_NOT_IN              = 50036
    | INVALID_ACTIVITY_ACTION                                      = 50039
    | INVALID_API_VERSION                                          = 50041
    | FILE_UPLOAD_EXCEEDS_MAX_SIZE                                 = 50045
    | INVALID_FILE_UPLOADED                                        = 50046
    | CANNOT_SELF_REDEEM_GIFT                                      = 50054
    | INVALID_GUILD                                                = 50055
    | INVALID_SKU                                                  = 50057
    | INVALID_REQUEST_ORIGIN                                       = 50067
    | INVALID_MESSAGE_TYPE                                         = 50068
    | PAYMENT_SOURCE_REQUIRED_TO_REDEEM_GIFT                       = 50070
    | CANNOT_MODIFY_SYSTEM_WEBHOOK                                 = 50073
    | CANNOT_DELETE_CHANNEL_REQUIRED_FOR_COMMUNITY_GUILDS          = 50074
    | CANNOT_EDIT_MESSAGE_STICKERS                                 = 50080
    | INVALID_STICKER_SENT                                         = 50081
    | INVALID_OPERATION_ON_ARCHIVED_THREAD                         = 50083
    | INVALID_THREAD_NOTIFICATION_SETTINGS                         = 50084
    | BEFORE_VALUE_EARLIER_THAN_THREAD_CREATION_DATE               = 50085
    | COMMUNITY_SERVER_CHANNELS_MUST_BE_TEXT_CHANNELS              = 50086
    | EVENT_ENTITY_TYPE_DIFFERENT_FROM_ENTITY_STARTING_EVENT       = 50091
    | SERVER_NEEDS_MONETIZATION_TO_PERFORM_THIS                    = 50097
    | SERVER_NEEDS_MORE_BOOSTS_TO_PERFORM_THIS                     = 50101
    | REQUEST_INVALID_JSON                                         = 50109
    | PROVIDED_FILE_INVALID                                        = 50110
    | PROVIDED_FILE_TYPE_INVALID                                   = 50123
    | PROVIDED_FILE_DURATION_EXCEEDS_MAX                           = 50124
    | OWNER_CANNOT_BE_PENDING_MEMBER                               = 50131
    | OWNERSHIP_CANNOT_BE_TRANSFERRED_TO_BOT                       = 50132
    | FAILED_TO_RESIZE_ASSET_BELOW_MAX_SIZE                        = 50138
    | CANNOT_MIX_SUBSCRIPTION_AND_NON_SUBSCRIPTION_ROLES_FOR_EMOJI = 50144
    | CANNOT_CONVERT_BETWEEN_PREMIUM_AND_NORMAL_EMOJI              = 50145
    | UPLOADED_FILE_NOT_FOUND                                      = 50146
    | SPECIFIED_EMOJI_INVALID                                      = 50151
    | VOICE_MESSAGES_DO_NOT_SUPPORT_ADDITIONAL_CONTENT             = 50159
    | VOICE_MESSAGES_MUST_HAVE_SINGLE_AUDIO_ATTACHMENT             = 50160
    | VOICE_MESSAGES_MUST_HAVE_SUPPORTING_METADATA                 = 50161
    | VOICE_MESSAGES_CANNOT_BE_EDITED                              = 50162
    | CANNOT_DELETE_GUILD_SUBSCRIPTION_INTEGRATION                 = 50163
    | CANNOT_SEND_VOICE_MESSAGES_IN_THIS_CHANNEL                   = 50173
    | USER_ACCOUNT_MUST_FIRST_BE_VERIFIED                          = 50178
    | PROVIDED_FILE_INVALID_DURATION                               = 50192
    | MISSING_PERMISSION_TO_SEND_STICKER                           = 50600
    | TWO_FACTOR_AUTH_REQUIRED_FOR_OPERATION                       = 60003
    | NO_USERS_WITH_DISCORD_TAG_EXIST                              = 80004
    | REACTION_BLOCKED                                             = 90001
    | USER_CANNOT_USE_BURST_REACTIONS                              = 90002
    | APPLICATION_NOT_YET_AVAILABLE                                = 110001
    | API_RESOURCE_CURRENTLY_OVERLOADED                            = 130000
    | STAGE_ALREADY_OPEN                                           = 150006
    | CANNOT_REPLY_WITHOUT_MESSAGE_HISTORY_PERMISSION              = 160002
    | THREAD_ALREADY_CREATED_FOR_MESSAGE                           = 160004
    | THREAD_LOCKED                                                = 160005
    | MAX_ACTIVE_THREADS_REACHED                                   = 160006
    | MAX_ACTIVE_ANNOUNCEMENT_THREADS_REACHED                      = 160007
    | INVALID_JSON_FOR_LOTTIE_FILE                                 = 170001
    | LOTTIES_CANNOT_CONTAIN_RASTERIZED_IMAGES                     = 170002
    | STICKER_MAX_FRAMERATE_EXCEEDED                               = 170003
    | STICKER_FRAME_COUNT_EXCEEDS_MAX_FRAMES                       = 170004
    | LOTTIE_ANIMATION_MAX_DIMENSTION_EXCEEDED                     = 170005
    | STICKER_FRAME_RATE_TOO_SMALL_OR_LARGE                        = 170006
    | STICKER_ANIMATION_DURATION_EXCEEDS_MAX                       = 170007
    | CANNOT_UPDATE_FINISHED_EVENT                                 = 180000
    | FAILED_TO_CREATE_STAGE_FOR_STAGE_EVENT                       = 180002
    | MESSAGE_BLOCKED_BY_AUTO_MODERATION                           = 200000
    | TITLE_BLOCKED_BY_AUTO_MODERATION                             = 200001
    | WENHOOK_POSTED_TO_FORUM_MUST_HAVE_THREAD_NAME_OR_ID          = 220001
    | WEBHOOK_POSTED_TO_FORUM_MUST_HAVE_BOT_THREAD_NAME_AND_ID     = 220002
    | WEBHOOK_CAN_ONLY_CREATE_THREAD_IN_FORUM_CHANNEL              = 220003
    | WEBHOOK_SERVICES_CANNOT_BE_USED_IN_FORUM_CHANNELS            = 220004
    | MESSAGE_BLOCKED_BY_HARMFUL_LINKS_FILTER                      = 240000
    | REQUIREMENTS_NOT_MET_TO_ENABLE_ONBOARDING                    = 350000
    | CANNOT_UPDATE_ONBOARDING_WHILE_BELOW_REQUIREMENTS            = 350001
    | FAILED_TO_BAN_USERS                                          = 500000
    | POLL_VOTING_BLOCKED                                          = 520000
    | POLL_EXPIRED                                                 = 520001
    | INVALID_CHANNEL_TYPE_FOR_POLL                                = 520002
    | CANNOT_EDIT_POLL_MESSAGE                                     = 520003
    | CANNOT_USE_EMOJI_INCLUDED_WITH_POLL                          = 520004
    | CANNOT_EXPIRE_NON_POLL_MESSAGE                               = 520006
    | APPLICATION_NOT_GRANTED_PROVISIONAL_ACCOUNTS_USE_PERMISSION  = 530000
    | JWT_ID_TOKEN_EXPIRED                                         = 530001
    | JWT_ID_TOKEN_ISSUER_DOES_NOT_MATCH                           = 530002
    | JWT_ID_TOKEN_AUDIENCE_DOES_NOT_MATCH                         = 530003
    | JWT_ID_TOKEN_ISSUED_TOO_LONG_AGO                             = 530004
    | DISCORD_FAILED_TO_GENERATE_UNIQUE_USERNAME_IN_TIME           = 530006
    | CLIENT_SECRET_INVALID                                        = 530007
